name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # ✅ Grant GitHub Actions write access to push changes
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate contribution snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: saisrinivasboga
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Show git status
        run: git status

      # ✅ Replace old push action with a better one
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update contribution graph"
          branch: master
